# ==============================================================================
# GRAFANA CLOUD SECRETS TEMPLATE
# ==============================================================================
# Instructions:
# 1. Replace all <PLACEHOLDERS> with your actual Grafana Cloud credentials.
# 2. Apply this file to your cluster:
#    kubectl apply -f k8s-secrets-template.yaml
# ==============================================================================

# ------------------------------------------------------------------------------
# Prometheus (Metrics)
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
type: Opaque
stringData:
  username: "<PASTE_PROMETHEUS_USERNAME_HERE>"
  password: "<PASTE_GRAFANA_CLOUD_API_KEY_HERE>"
  url: "<PASTE_PROMETHEUS_URL_HERE>" # e.g., https://prometheus-prod-xx-xx-xx.grafana.net/api/prom/push

---
# ------------------------------------------------------------------------------
# Loki (Logs)
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-loki
  namespace: monitoring
type: Opaque
stringData:
  username: "<PASTE_LOKI_USERNAME_HERE>"
  password: "<PASTE_GRAFANA_CLOUD_API_KEY_HERE>"
  url: "<PASTE_LOKI_URL_HERE>" # e.g., https://logs-prod-xx-xx-xx.grafana.net/loki/api/v1/push

---
# ------------------------------------------------------------------------------
# Tempo (Traces)
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-tempo
  namespace: monitoring
type: Opaque
stringData:
  username: "<PASTE_TEMPO_USERNAME_HERE>"
  password: "<PASTE_GRAFANA_CLOUD_API_KEY_HERE>"
  endpoint: "<PASTE_TEMPO_ENDPOINT_HERE>" # e.g., tempo-prod-xx-xx-xx.grafana.net:443 (No https://)

---
# ------------------------------------------------------------------------------
# Pyroscope (Profiling)
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-pyroscope
  namespace: monitoring
type: Opaque
stringData:
  username: "<PASTE_PYROSCOPE_USERNAME_HERE>"
  password: "<PASTE_GRAFANA_CLOUD_API_KEY_HERE>"
  url: "<PASTE_PYROSCOPE_URL_HERE>" #

---
# ------------------------------------------------------------------------------
# Faro (Frontend Observability)
# ------------------------------------------------------------------------------
apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-faro
  namespace: pov-sim
type: Opaque
stringData:
  endpoint: "<PASTE_FARO_COLLECTOR_URL_HERE>" # e.g., https://faro-collector-prod-xx-xx-xx.grafana.net/collect/your_app_key