apiVersion: v1  
kind: Service  
metadata:  
  name: kube-state-metrics  
  namespace: monitoring  
  labels:  
    app.kubernetes.io/name: kube-state-metrics  
    app.kubernetes.io/instance: kube-state-metrics  
    app.kubernetes.io/component: metrics  
spec:  
  type: ClusterIP  
  ports:  
  - name: http  
    port: 8080  
    targetPort: 8080  
    protocol: TCP  
  selector:  
    app.kubernetes.io/name: kube-state-metrics  
    app.kubernetes.io/instance: kube-state-metrics  