apiVersion: v1
kind: Service
metadata:
  name: {{ include "pov-sim.fullname" . }}-airlines
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "pov-sim.labels" . | nindent 4 }}
    app.kubernetes.io/component: airlines
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pov-sim.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: airlines